apiVersion: v1
kind: Service
metadata:
  name: basic-app
  namespace: basic-app
spec:
  selector:
    app: basic-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP 