name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
  pull_request:
    branches: [ main ]

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE: mertpolatace/basic-todo-api
  K8S_DEPLOYMENT_FILE: k8s/app/deployment.yaml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_TOKEN }}
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Generate Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}
        tags: |
          type=sha,format=long
          type=raw,value=latest
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Update Kubernetes deployment
      if: github.event_name != 'pull_request'
      run: |
        NEW_IMAGE="${{ env.DOCKER_IMAGE }}@${{ steps.meta.outputs.digest }}"
        sed -i "s|${{ env.DOCKER_IMAGE }}:.*|${NEW_IMAGE}|" ${{ env.K8S_DEPLOYMENT_FILE }}
    
    - name: Commit and push changes
      if: github.event_name != 'pull_request'
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ${{ env.K8S_DEPLOYMENT_FILE }}
        git commit -m "chore: Update image tag to ${{ github.sha }}" || echo "No changes to commit"
        git push